### ISSUE TITLE
GPS status indication.

### ISSUE THREAD

**Issue by 9600** [DesignSparkRS/aq-device#25]
Add a GPS indicator to the screen, e.g. small icon:

* Grey = GPS not enabled
* Green = enabled and has a fix
* Red = enabled and no fix

**Comment by callumsnowden** [comment]
Implemented in https://github.com/DesignSparkRS/aq-device/commit/4ba9cac8365b344d82975e6dceea7073ec1165f9

GPS status icon is not coloured at present as this could be confusing due to coloured metric tile beneath icon, but instead swaps between three states:
- No icon visible if no GPS status present (GPS disabled)
- Hollow crosshair for GPS status, but no lock
- Filled crosshair for GPS locked
